--R1:Tên đề tài phải duy nhất

CREATE 
--ALTER
TRIGGER UTR_1
ON DETAI 
FOR UPDATE ,INSERT 
AS 
IF UPDATE (TENDT)
	BEGIN 
		IF EXISTS ( SELECT * FROM inserted I JOIN DETAI DT ON DT.MADT=I.MADT
					WHERE I.TENDT = DT.TENDT )
		BEGIN
			RAISERROR ('LOI R1',16,1 )
			ROLLBACK 
		END
	END 
GO 
--R3: Một bộ môn có tối thiểu một giáo viên nữ 
CREATE 
--ALTER
TRIGGER UTR_3
ON GIAOVIEN
FOR INSERT
AS 
 --NEU VI PHAM 
	IF EXISTS (SELECT COUNT (GV.PHAI) 
			   FROM inserted I JOIN GIAOVIEN GV ON I.MAGV=GV.MAGV JOIN BOMON BM ON BM.MABM=GV.MABM
			   WHERE I.PHAI=N'Nữ'
			   GROUP BY GV.MAGV , BM.MABM
			   HAVING COUNT(GV.PHAI)<1)
	BEGIN 
		RAISERROR ('LOI R3' ,16,1)
		ROLLBACK
	END
GO 
SELECT * FROM GIAOVIEN

--DELETE GIAOVIEN WHERE MAGV ='002'
--R5 : Một giáo viên có tối đa 3 số điện thoại
CREATE TRIGGER UTR_5
ON GV_DT
FOR INSERT
AS 
 --NEU VI PHAM 
	IF EXISTS (SELECT COUNT (*) 
			   FROM INSERTED I JOIN GV_DT DT ON DT.MAGV=I.MAGV
			   HAVING COUNT(*)>3)
	BEGIN 
		RAISERROR ('LOI R5' ,16,1)
		ROLLBACK
	END
GO 

--R7 : TRUONG BO MON PHAI LA NGUOI LON TUOI NHAT BO MON
CREATE TRIGGER UTR_7
ON GIAOVIEN
FOR UPDATE , INSERT
AS
	IF UPDATE (NGSINH)
	BEGIN 
		IF EXISTS ( SELECT * FROM inserted I JOIN BOMON BM ON BM.MABM= I.MABM JOIN GIAOVIEN GV ON GV.MAGV=BM.TRUONGBM
					WHERE I.NGSINH < GV.NGSINH )
		BEGIN
			RAISERROR ('LOI R7',16,1 )
			ROLLBACK 
		END
	END 
GO