--20127395-PHAN MINH XUÂN
--20127444-BÙI DUY BẢO 
--20127448-NGUYỄN THÁI BẢO


-- CÂU 1A - QUẢN LÍ NGÀNH 
USE MASTER 
GO
IF DB_ID('QL') IS NOT NULL
	DROP DATABASE QL
GO
CREATE DATABASE QL
GO
USE QL
GO
--TAO BANG
CREATE TABLE SINHVIEN
(
	MASV CHAR(8) UNIQUE,
	HOTEN NVARCHAR(30) NOT NULL,
	PHAI NVARCHAR(5),
	NGAYSINH DATETIME,
	DCHI NVARCHAR(30),
	MANGANH CHAR(3)

	CONSTRAINT PK_SINHVIEN
	PRIMARY KEY(MASV)
)

CREATE TABLE NGANH
(
	MANGANH CHAR(3) UNIQUE,
	TENNGANH NVARCHAR(30) UNIQUE,
	SOCD SMALLINT,
	TSSV INT

	CONSTRAINT PK_NGANH
	PRIMARY KEY(MANGANH)
)

CREATE TABLE CHUYENDE
(
	MACD CHAR(3) UNIQUE,
	TENCD NVARCHAR(30) UNIQUE,
	SOSVTD INT

	CONSTRAINT PK_CHUYENDE
	PRIMARY KEY(MACD)
)

CREATE TABLE CD_NGANH
(
	MACD CHAR(3),
	MANGANH CHAR(3)

	CONSTRAINT PK_CD_NGANH
	PRIMARY KEY(MACD,MANGANH)
)

CREATE TABLE CD_MO
(
	MACD CHAR(3),
	HOCKY TINYINT,
	NAM SMALLINT

	CONSTRAINT PK_CD_MO
	PRIMARY KEY(MACD)
)

CREATE TABLE DANGKY
(
	MASV CHAR(8),
	MACD CHAR(3),
	HOCKY TINYINT,
	NAM SMALLINT,
	DIEM FLOAT

	CONSTRAINT PK_DANGKY
	PRIMARY KEY(MASV,MACD,HOCKY)
)

--KHOA NGOAI
ALTER TABLE SINHVIEN
ADD
	CONSTRAINT FK_SINHVIEN_NGANH
	FOREIGN KEY(MANGANH)
	REFERENCES NGANH,

	CONSTRAINT CHECK_SINHVIEN_PHAI
	CHECK(PHAI IN (N'NAM',N'NỮ'))



ALTER TABLE CD_NGANH
ADD
	CONSTRAINT FK_CDNGANH_NGANH
	FOREIGN KEY(MANGANH)
	REFERENCES NGANH,

	CONSTRAINT FK_CDNGANH_CHUYENDE
	FOREIGN KEY(MACD)
	REFERENCES CHUYENDE

ALTER TABLE CD_MO
ADD
	CONSTRAINT FK_CDMO_CHUYENDE
	FOREIGN KEY(MACD)
	REFERENCES CHUYENDE

ALTER TABLE DANGKY
ADD
	CONSTRAINT FK_DANGKY_CDMO
	FOREIGN KEY(MACD)
	REFERENCES CD_MO,

	CONSTRAINT FK_DANGKY_SINHVIEN
	FOREIGN KEY(MASV)
	REFERENCES SINHVIEN,

	CONSTRAINT CHECK_DANGKY_DIEM
	CHECK (0 <= DIEM AND DIEM <= 10)


	--CÂU 1B - QUẢN LÍ NHÀ CUNG CẤP 
	USE MASTER
GO
IF DB_ID('QuanLyNha')IS NOT NULL
	DROP DATABASE QuanLyNha
GO
CREATE DATABASE QuanLyNha
GO
USE QuanLyNha
GO

CREATE TABLE NHACC(
	MANCC CHAR(5),
	TENNCC NVARCHAR(50),
	DIACHI NVARCHAR(50),
	DT CHAR(10)

	CONSTRAINT PK_NHACC
	PRIMARY KEY (MANCC)
)
CREATE TABLE HANGHOA(
	MAHH CHAR(5),
	TENHH NVARCHAR(50),
	DVT NVARCHAR(50),
	QUYCACH NVARCHAR(50),
	SLTON NVARCHAR(50)

	CONSTRAINT PK_HANGHOA
	PRIMARY KEY(MAHH)
)

CREATE TABLE CUNGUNG(
	MANCC CHAR(5),
	MAHH CHAR(5)

	CONSTRAINT PK_CUNGUNG
	PRIMARY KEY(MANCC,MAHH)
)
CREATE TABLE DDH(
	SODDH CHAR(5) UNIQUE,
	NGAYDH CHAR(5),
	MANCC CHAR(5)

	CONSTRAINT PK_DDH
	PRIMARY KEY(SODDH)
)
CREATE TABLE CTDDH(
	SODDH CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50)

	CONSTRAINT PK_CTDHH
	PRIMARY KEY(SODDH,MAHH)

)
CREATE TABLE GIAOHANG(
	SOGH CHAR(5) UNIQUE,
	NGAYGH CHAR(5),
	SODDH CHAR(5)

	CONSTRAINT PK_GIAOHANG
	PRIMARY KEY(SOGH)
)
CREATE TABLE CTGH(
	SOGH CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50)

	CONSTRAINT PK_CTGH
	PRIMARY KEY (SOGH,MAHH)
)
CREATE TABLE HOADON(
	SOHD CHAR(5) UNIQUE,
	NGAYHD CHAR(5),
	TENKH NVARCHAR(50)

	CONSTRAINT PK_HOADON
	PRIMARY KEY(SOHD)
)
CREATE TABLE CTHD(
	SOHD CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50),
	DONGIA NVARCHAR(50)

	CONSTRAINT PK_CTHD
	PRIMARY KEY(SOHD,MAHH)
)
ALTER TABLE CUNGUNG
ADD
	CONSTRAINT FK_CUNGUNG_NHACC
	FOREIGN KEY(MANCC)
	REFERENCES NHACC,

	CONSTRAINT FK_CUNGUNG_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE DDH
ADD
	CONSTRAINT FK_DDH_NHACC
	FOREIGN KEY(MANCC)
	REFERENCES NHACC

ALTER TABLE CTDDH
ADD
	CONSTRAINT FK_CTDDH_DDH
	FOREIGN KEY(SODDH)
	REFERENCES DDH,

	CONSTRAINT FK_CTDDH_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE GIAOHANG
ADD
	CONSTRAINT FK_GIAOHANG_DDH
	FOREIGN KEY(SODDH)
	REFERENCES DDH

ALTER TABLE CTGH
ADD
	CONSTRAINT FK_CTGH_GIAOHANG
	FOREIGN KEY(SOGH)
	REFERENCES GIAOHANG,

	CONSTRAINT FK_CTGH_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE CTHD
ADD
	CONSTRAINT FK_CTHD_HOADON
	FOREIGN KEY(SOHD)
	REFERENCES HOADON,

	CONSTRAINT FK_CTHD_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA


--CÂU 1C -QUẢN LÍ ĐỀ ÁN 
IF DB_ID('QLDEAN') IS NOT NULL 
	DROP DATABASE QLDEAN 
GO 
CREATE DATABASE QLDEAN 
GO
USE QLDEAN 
GO
CREATE TABLE DEAN(
	MADA CHAR(10) UNIQUE,
	NGAYBD DATETIME,
	NGAYKT DATETIME,
	TTRANG NVARCHAR(20),
	MAPB CHAR(10),
	CHIPHIDDA FLOAT
	constraint PK_DEAN primary key(MADA)
)
CREATE TABLE CONGDOAN(
	MADA CHAR(10),
	STTCD INT UNIQUE,
	NGAYBD DATETIME,
	NGAYKT DATETIME,
	MACV CHAR(10)
	constraint PK_CONGDOAN primary key (STTCD)
	constraint FK_congdoan_dean foreign key (MADA) references DEAN(MADA)
)
CREATE TABLE THAMGIACD(
	MANV CHAR(10),
	MADA CHAR(10),
	STTCD INT
	constraint PK_THAMGIACD primary key (MANV,STTCD)
	constraint FK_thamgiacd_congdoan foreign key (STTCD) references CONGDOAN(STTCD)
)

CREATE TABLE CONGVIEC(
	MACV CHAR(10) UNIQUE,
	TENCV NVARCHAR(50),
	CHIPHICV FLOAT
	constraint PK_CONGVIEC primary key (MACV)	
	constraint C_chiphi check (CHIPHICV >=0)
)
CREATE TABLE KHANANG(
	MANV CHAR(10),
	MACV CHAR(10)
	constraint PK_KHANANG primary key(MANV)
	constraint FK_khanang_congviec foreign key (MACV) references CONGVIEC(MACV)
)


ALTER TABLE CONGDOAN
ADD constraint FK_congdoan_congviec foreign key (MACV) references CONGVIEC(MACV)
ALTER TABLE THAMGIACD
ADD constraint FK_thamgiacd_khanang foreign key (MANV) references KHANANG(MANV)



--CÂU 2 TRUY VẤN 
--CAU A
SELECT DA.TENDA ,DA.MADA ,DA.DDIEM_DA
FROM DEAN DA

--CAU B
SELECT CV.TEN_CONG_VIEC
FROM CONGVIEC CV
WHERE CV.TEN_CONG_VIEC LIKE N'% san pham X'

--CAU C
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN],DATEDIFF(YEAR,NV.NGSINH,GETDATE()) [TUỔI] ,NV.DCHI ,NV.LUONG+NV.LUONG*0.05 [LƯƠNG TĂNG 5%]
FROM NHANVIEN NV 
ORDER BY [HỌ TÊN] ASC,[TUỔI] DESC

--CAU D
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN],NV.DCHI
FROM NHANVIEN NV ,PHONGBAN PB
WHERE PB.MAPHG = NV.PHG AND PB.MAPHG=1 AND NV.PHAI=N'Nam'

--CAU E 
SELECT  *
FROM NHANVIEN NV
WHERE  DATEDIFF (YEAR,NV.NGSINH,GETDATE()) >40 OR NV.DCHI LIKE N'% HÀ NỘI'

--CAU F
SELECT TENNV
FROM PHONGBAN PB , NHANVIEN NV--> TÍCH ĐỀ CÁC
WHERE (PB.MAPHG = NV.PHG AND PB.TRPHG=NV.MANV AND TENPHG= N'ĐIỀU HÀNH' ) OR (PB.MAPHG = NV.PHG AND PB.TRPHG=NV.MANV AND YEAR(NG_NHANCHUC)>1980 )

--CAU G
SELECT NV1.TENNV N'Tên nhân viên', NV2.TENNV N'Tên NQLCM'
FROM NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.MA_NQL = NV2.MANV

--CAU H
SELECT  TN.TENTN, NV.TENNV
FROM NHANVIEN NV, THANNHAN TN
WHERE (NV.MANV=TN.MA_NVIEN) OR (NV.LUONG<25000) OR ( NV.MA_NQL IS NULL)

--CAU I
SELECT  TN.TENTN
FROM NHANVIEN NV, THANNHAN TN
WHERE (NV.MANV=TN.MA_NVIEN AND TN.QUANHE=N'Vợ chồng' AND NV.HONV=N'NGUYỄN') OR (NV.MANV=TN.MA_NVIEN AND DATEDIFF(YEAR, NV.NGSINH,GETDATE ()) >50)

--CAU J
SELECT TN.TENTN
FROM THANNHAN TN , PHONGBAN PB
WHERE TN.MA_NVIEN= PB.TRPHG AND PB.TENPHG=N'Nghiên cứu' AND TN.QUANHE LIKE N'Con %'

--CAU K
SELECT DISTINCT DD.DIADIEM
FROM DIADIEM_PHG DD

--CAU L
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN]
FROM CONGVIEC CV ,PHANCONG PC ,NHANVIEN NV
WHERE CV.MADA=PC.MADA AND PC.MA_NVIEN =NV.MANV AND CV.TEN_CONG_VIEC=N'Lap dat cap quang'

--CAU M
SELECT DA.TENDA,CV.TEN_CONG_VIEC ,NV.TENNV
FROM CONGVIEC CV ,PHANCONG PC ,NHANVIEN NV,DEAN DA
WHERE CV.MADA=PC.MADA AND PC.MA_NVIEN =NV.MANV AND CV.MADA =DA.MADA AND PC.THOIGIAN BETWEEN 10 AND 25