--20127395-PHAN MINH XUÂN

-- TRUY VẤN 
--Q1
SELECT GV.HOTEN ,GV.LUONG
FROM GIAOVIEN GV
WHERE GV.PHAI=N'Nữ'

--Q3
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV , BOMON BM
WHERE ( GV.HOTEN LIKE N'Nguyễn %' AND GV.LUONG>2000) OR (GV.MAGV =BM.TRUONGBM AND YEAR(BM.NGAYNHANCHUC) >1995)

--Q5
SELECT DISTINCT BM.MABM,BM.TENBM, GV.MAGV
FROM GIAOVIEN GV , BOMON BM
WHERE GV.MAGV =BM.TRUONGBM

--Q7
SELECT DT.TENDT ,GV.HOTEN
FROM GIAOVIEN GV , DETAI DT
WHERE GV.MAGV = DT.GVCNDT

--Q9
SELECT  GV.HOTEN
FROM GIAOVIEN GV , BOMON BM, DETAI DT
WHERE GV.MAGV =BM.TRUONGBM AND BM.TENBM=N'VI SINH' AND DT.MADT='006'

--Q11 
SELECT  GV1.HOTEN N'GIÁO VIÊN', GV2.HOTEN N'GIÁO VIÊN QUẢN LÍ CHUYÊN MÔN'
FROM GIAOVIEN GV1 ,GIAOVIEN GV2
WHERE GV1.MAGV=GV2.GVQLCM

--Q13
SELECT GV.HOTEN
FROM GIAOVIEN GV , BOMON BM
WHERE GV.MAGV =BM.TRUONGBM AND BM.TENBM=N'HỆ THỐNG THÔNG TIN'

--Q15 
SELECT CV.TENCV
FROM DETAI DT , CONGVIEC CV
WHERE DT.MADT=CV.MADT AND DT.TENDT=N'HTTT quản lý các trường ĐH' AND   CV.NGAYBD BETWEEN  '03/01/2008' AND '03/31/2008'

--Q17
SELECT CV.TENCV
FROM CONGVIEC CV 
WHERE CV.NGAYBD BETWEEN '01/01/2007' AND '08/01/2007'

--Q19
SELECT DISTINCT GV.HOTEN
FROM DETAI DT ,BOMON BM, GIAOVIEN GV
WHERE DT.GVCNDT=BM.TRUONGBM AND GV.MAGV=BM.TRUONGBM

--Q21
SELECT DISTINCT GV.HOTEN
FROM DETAI DT ,BOMON BM, GIAOVIEN GV
WHERE DT.GVCNDT=BM.TRUONGBM AND GV.MAGV=BM.TRUONGBM

--Q23 
SELECT DISTINCT GV.MAGV
FROM DETAI DT ,BOMON BM, GIAOVIEN GV
WHERE (GV.MABM=BM.MABM  AND BM.MABM ='HTTT') OR (DT.GVCNDT=GV.MAGV  AND DT.MADT='001' )

--Q25
SELECT  GV.HOTEN
FROM GIAOVIEN GV , BOMON BM
WHERE GV.MAGV=BM.TRUONGBM