--20127395- Phan Minh Xuân
--TRUY VẤN QUẢN LÍ ĐỀ TÀI 
--Q2
SELECT  GV.HOTEN ,GV.LUONG*1.1  N'LƯƠNG TĂNG 10%'
FROM GIAOVIEN GV 
--Q4
SELECT GV.HOTEN
FROM GIAOVIEN GV , KHOA K
WHERE K.TRUONGKHOA=GV.MAGV AND K.TENKHOA=N'Công nghệ thông tin'
--Q6
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV , BOMON BM
WHERE GV.MABM=BM.MABM
--Q8
SELECT *
FROM GIAOVIEN GV , KHOA K
WHERE K.TRUONGKHOA=GV.MAGV 
--Q10
SELECT DT.MADT ,CD.TENCD,GV.HOTEN 
FROM DETAI DT, CHUDE CD,GIAOVIEN GV
WHERE DT.GVCNDT=GV.MAGV AND CD.MACD=DT.MACD AND DT.CAPQL =N'Thành phố'
--Q12
SELECT GV1.HOTEN
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.MAGV=GV2.GVQLCM AND GV2.HOTEN=N'Nguyễn Thanh Tùng'
--Q14
SELECT DISTINCT GV.HOTEN
FROM DETAI DT, GIAOVIEN GV,CHUDE CD
WHERE DT.GVCNDT=GV.MAGV AND CD.MACD=DT.MACD AND CD.TENCD=N'Quản lý giáo dục'
--Q16
SELECT GV2.HOTEN , GV1.HOTEN AS N'GIÁO VIÊN QUẢN LÍ CHUYÊN MÔN'
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.MAGV =GV2.GVQLCM
--Q18 
SELECT GV2.HOTEN
FROM GIAOVIEN GV1 ,GIAOVIEN GV2
WHERE GV1.MABM =GV2.MABM AND GV1.MAGV='002' AND GV2.MAGV <>'002'
--Q20
SELECT DISTINCT GV.HOTEN 
FROM KHOA K, GIAOVIEN GV , BOMON BM
WHERE  GV.MAGV= K.TRUONGKHOA AND GV.MAGV =BM.TRUONGBM
--Q22 
SELECT DISTINCT GV.MAGV
FROM KHOA K, DETAI DT ,GIAOVIEN GV
WHERE DT.GVCNDT =GV.MAGV AND GV.MAGV=K.TRUONGKHOA
--Q24 
SELECT GV2.MAGV,GV2.HOTEN
FROM GIAOVIEN GV1 ,GIAOVIEN GV2
WHERE GV1.MABM =GV2.MABM AND GV1.MAGV='002' AND GV2.MAGV <>'002'
--Q26
SELECT GV.HOTEN ,GV.LUONG
FROM GIAOVIEN GV

--TRUY VẤN QUẢN LÍ CHUYẾN BAY 


--Q1
SELECT NV.MANV, NV.TEN, NV.DCHI,NV.DTHOAI
FROM NHANVIEN NV JOIN PHANCONG PC ON PC.MANV=NV.MANV JOIN LICHBAY LB ON PC.MACB=LB.MACB AND LB.MALOAI='B747' AND NV.LOAINV=1
--Q2
SELECT CB.MACB , LB.NGAYDI
FROM CHUYENBAY CB JOIN LICHBAY LB ON CB.MACB =LB.MACB AND CB.SBDI='DCA' AND CB.GIODI BETWEEN '14:00' AND '18:00'
--Q3
SELECT DISTINCT NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.MANV=PC.MANV JOIN CHUYENBAY CB ON CB.MACB = PC.MACB AND CB.MACB ='100' AND CB.SBDI ='SLC'
--Q4
SELECT DISTINCT LB.MALOAI , LB.SOHIEU
FROM CHUYENBAY CB JOIN LICHBAY LB ON LB.MACB =CB.MACB AND CB.SBDI='MIA'
--Q5
SELECT DC.MACB ,DC.NGAYDI,KH.TEN , KH.DCHI , KH.DTHOAI
FROM  DATCHO DC  JOIN KHACHHANG KH ON KH.MAKH=DC.MAKH 
ORDER BY DC.MACB ASC ,DC.NGAYDI DESC
--Q6
SELECT  PC.MACB ,PC.NGAYDI,NV.TEN , NV.DCHI , NV.DTHOAI
FROM  PHANCONG PC  JOIN NHANVIEN NV ON NV.MANV=PC.MANV 
ORDER BY PC.MACB ASC ,PC.NGAYDI DESC
--Q7
SELECT  LB.MACB ,LB.NGAYDI,NV.MANV,NV.TEN 
FROM LICHBAY LB JOIN PHANCONG PC ON LB.MACB=PC.MACB JOIN NHANVIEN NV ON NV.MANV=PC.MANV JOIN CHUYENBAY CB ON CB.MACB=LB.MACB AND CB.SBDEN='ORD' AND NV.LOAINV=1
--Q8 
SELECT PC.MACB ,PC.NGAYDI, NV.TEN
FROM PHANCONG PC  JOIN NHANVIEN NV ON NV.MANV =PC.MANV AND NV.LOAINV=1 AND NV.MANV='1001'
--Q9
SELECT CB.MACB, CB.SBDI, CB.GIODI ,CB.GIODEN ,LB.NGAYDI
FROM CHUYENBAY CB , LICHBAY LB
WHERE CB.MACB = LB.MACB AND CB.SBDEN ='DEN'
ORDER BY LB.NGAYDI DESC , CB.SBDI ASC
--Q10
SELECT NV.TEN , L.HANGSX , L.MALOAI
FROM NHANVIEN NV JOIN KHANANG KN ON KN.MANV=NV.MANV JOIN LOAIMB L ON L.MALOAI =KN.MALOAI AND NV.LOAINV=1
--Q11
SELECT DISTINCT NV.MANV , NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON PC.MANV=NV.MANV AND NV.LOAINV=1 AND PC.MACB='100' AND PC.NGAYDI='11/01/2000'
--Q12
SELECT DISTINCT CB.MACB,NV.MANV , NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON PC.MANV=NV.MANV JOIN CHUYENBAY CB ON CB.MACB =PC.MACB JOIN LICHBAY LB ON LB.MACB = CB.MACB AND LB.NGAYDI='10/31/2000' AND CB.SBDI='MIA' AND CB.GIODI='20:30'
--Q13
SELECT DISTINCT PC.MACB ,LB.SOHIEU,L.MALOAI, L.HANGSX
FROM NHANVIEN NV  JOIN PHANCONG PC ON PC.MANV=NV.MANV JOIN LICHBAY LB ON LB.MACB = PC.MACB JOIN LOAIMB L ON L.MALOAI =LB.MALOAI AND NV.TEN='Quang' AND NV.LOAINV=1
--Q14
SELECT NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON NV.LOAINV=1 AND NV.MANV NOT IN (SELECT MANV FROM PHANCONG)
--Q15
SELECT DISTINCT KH.TEN
FROM KHACHHANG KH JOIN DATCHO DC ON DC.MAKH= KH.MAKH JOIN LICHBAY LB ON LB.MACB = DC .MACB JOIN MAYBAY MB ON MB.MALOAI = LB.MALOAI JOIN LOAIMB L ON L.MALOAI =MB.MALOAI AND L.HANGSX='Boeing'
--Q16
SELECT DISTINCT LB.MACB
FROM LICHBAY LB
WHERE LB.SOHIEU=10 AND LB.MALOAI ='B747'
