USE MASTER
GO
IF DB_ID('QuanLyNha')IS NOT NULL
	DROP DATABASE QuanLyNha
GO
CREATE DATABASE QuanLyNha
GO
USE QuanLyNha
GO

CREATE TABLE NHACC(
	MANCC CHAR(5),
	TENNCC NVARCHAR(50),
	DIACHI NVARCHAR(50),
	DT CHAR(10)

	CONSTRAINT PK_NHACC
	PRIMARY KEY (MANCC)
)
CREATE TABLE HANGHOA(
	MAHH CHAR(5),
	TENHH NVARCHAR(50),
	DVT NVARCHAR(50),
	QUYCACH NVARCHAR(50),
	SLTON NVARCHAR(50)

	CONSTRAINT PK_HANGHOA
	PRIMARY KEY(MAHH)
)
CREATE TABLE CUNGUNG(
	MANCC CHAR(5),
	MAHH CHAR(5)

	CONSTRAINT PK_CUNGUNG
	PRIMARY KEY(MANCC,MAHH)
)
CREATE TABLE DDH(
	SODDH CHAR(5),
	NGAYDH CHAR(5),
	MANCC CHAR(5)

	CONSTRAINT PK_DDH
	PRIMARY KEY(SODDH)
)
CREATE TABLE CTDDH(
	SODDH CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50)

	CONSTRAINT PK_CTDHH
	PRIMARY KEY(SODDH,MAHH)

)
CREATE TABLE GIAOHANG(
	SOGH CHAR(5),
	NGAYGH CHAR(5),
	SODDH CHAR(5)

	CONSTRAINT PK_GIAOHANG
	PRIMARY KEY(SOGH)
)
CREATE TABLE CTGH(
	SOGH CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50)

	CONSTRAINT PK_CTGH
	PRIMARY KEY (SOGH,MAHH)
)
CREATE TABLE HOADON(
	SOHD CHAR(5),
	NGAYHD CHAR(5),
	TENKH NVARCHAR(50)

	CONSTRAINT PK_HOADON
	PRIMARY KEY(SOHD)
)
CREATE TABLE CTHD(
	SOHD CHAR(5),
	MAHH CHAR(5),
	SOLUONG NVARCHAR(50),
	DONGIA NVARCHAR(50)

	CONSTRAINT PK_CTHD
	PRIMARY KEY(SOHD,MAHH)
)
ALTER TABLE CUNGUNG
ADD
	CONSTRAINT FK_CUNGUNG_NHACC
	FOREIGN KEY(MANCC)
	REFERENCES NHACC,

	CONSTRAINT FK_CUNGUNG_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE DDH
ADD
	CONSTRAINT FK_DDH_NHACC
	FOREIGN KEY(MANCC)
	REFERENCES NHACC

ALTER TABLE CTDDH
ADD
	CONSTRAINT FK_CTDDH_DDH
	FOREIGN KEY(SODDH)
	REFERENCES DDH,

	CONSTRAINT FK_CTDDH_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE GIAOHANG
ADD
	CONSTRAINT FK_GIAOHANG_DDH
	FOREIGN KEY(SODDH)
	REFERENCES DDH

ALTER TABLE CTGH
ADD
	CONSTRAINT FK_CTGH_GIAOHANG
	FOREIGN KEY(SOGH)
	REFERENCES GIAOHANG,

	CONSTRAINT FK_CTGH_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA

ALTER TABLE CTHD
ADD
	CONSTRAINT FK_CTHD_HOADON
	FOREIGN KEY(SOHD)
	REFERENCES HOADON,

	CONSTRAINT FK_CTHD_HANGHOA
	FOREIGN KEY(MAHH)
	REFERENCES HANGHOA


