--20127395-PHAN MINH XUÂN
--20127444-BÙI DUY BẢO 
--20127448-NGUYỄN THÁI BẢO

--CAU A
SELECT DA.TENDA ,DA.MADA ,DA.DDIEM_DA
FROM DEAN DA

--CAU B
SELECT CV.TEN_CONG_VIEC
FROM CONGVIEC CV
WHERE CV.TEN_CONG_VIEC LIKE N'% san pham X'

--CAU C
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN],DATEDIFF(YEAR,NV.NGSINH,GETDATE()) [TUỔI] ,NV.DCHI ,NV.LUONG+NV.LUONG*0.05 [LƯƠNG TĂNG 5%]
FROM NHANVIEN NV 
ORDER BY [HỌ TÊN] ASC,[TUỔI] DESC

--CAU D
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN],DATEDIFF(YEAR,NV.NGSINH,GETDATE()) [TUỔI] ,NV.DCHI
FROM NHANVIEN NV ,PHONGBAN PB
WHERE PB.MAPHG = NV.PHG AND PB.MAPHG=1 AND NV.PHAI=N'NAM'

--CAU E 
SELECT  *
FROM NHANVIEN NV
WHERE  DATEDIFF (YEAR,NV.NGSINH,GETDATE()) >40 OR NV.DCHI LIKE N'% HÀ NỘI'

--CAU F
SELECT TENNV
FROM PHONGBAN PB , NHANVIEN NV--> TÍCH ĐỀ CÁC
WHERE (PB.MAPHG = NV.PHG AND PB.TRPHG=NV.MANV AND TENPHG= N'ĐIỀU HÀNH' ) OR (PB.MAPHG = NV.PHG AND PB.TRPHG=NV.MANV AND YEAR(NG_NHANCHUC)>1980 )

--CAU 
SELECT NV1.TENNV N'Tên nhân viên', NV2.TENNV N'Tên NQLCM'
FROM NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.MA_NQL = NV2.MANV

--CAU H
SELECT  TN.TENTN, NV.TENNV
FROM NHANVIEN NV, THANNHAN TN
WHERE (NV.MANV=TN.MA_NVIEN) OR (NV.LUONG<25000) OR ( NV.MA_NQL IS NULL)

--CAU I
SELECT  TN.TENTN
FROM NHANVIEN NV, THANNHAN TN
WHERE (NV.MANV=TN.MA_NVIEN AND TN.QUANHE=N'Vợ chồng' AND NV.HONV=N'NGUYỄN') OR (NV.MANV=TN.MA_NVIEN AND DATEDIFF(YEAR, NV.NGSINH,GETDATE ()) >50)

--CAU J
SELECT TN.TENTN
FROM THANNHAN TN , PHONGBAN PB
WHERE TN.MA_NVIEN= PB.TRPHG AND PB.TENPHG=N'Nghiên cứu' AND TN.QUANHE LIKE N'Con %'

--CAU K
SELECT DISTINCT DD.DIADIEM
FROM DIADIEM_PHG DD

--CAU L
SELECT NV.HONV+' '+NV.TENLOT+' '+ NV.TENNV [HỌ TÊN]
FROM CONGVIEC CV ,PHANCONG PC ,NHANVIEN NV
WHERE CV.MADA=PC.MADA AND PC.MA_NVIEN =NV.MANV AND CV.TEN_CONG_VIEC=N'Lap dat cap quang'

--CAU M
SELECT DA.TENDA,CV.TEN_CONG_VIEC ,NV.TENNV
FROM CONGVIEC CV ,PHANCONG PC ,NHANVIEN NV,DEAN DA
WHERE CV.MADA=PC.MADA AND PC.MA_NVIEN =NV.MANV AND CV.MADA =DA.MADA AND PC.THOIGIAN BETWEEN 10 AND 25